#####################################################################
#
#  This default config file outlines most of the configuration
#   possible using this software, probably don't uncomment it all
#
#####################################################################

controllers:
  - unit: 1
    type: g3
    devices:
      1: Riing Plus
      2: Riing Plus
      3: Riing Plus
      4: Riing Plus
      5: Floe Riing RGB
#  - unit: 1
#    type: riingtrio
#    devices:
#      1: Riing Plus  # These are incorrectly specified as Riing Plus
#      2: Riing Plus  # there is nothing in the code that will break this
#      3: Riing Plus  # but we should not be doing confusing things like this
#                     # TODO: implement better fan naming schemes
#  - unit: 2
#    type: g3
#    devices:
#      1: Riing Plus
#      2: Riing Plus
#      3: Riing Plus
#      4: Pacific V-GTX 1080Ti Plus GPU Waterblock
#      5: Pacific W4 Plus CPU Waterblock
#  - unit: 3
#    type: g3
#    devices:
#      1: Riing Plus
#      2: Riing Plus
#      3: Riing Plus
#      4: Pacific V-GTX 1080Ti Plus GPU Waterblock
#      5: Pacific PR22-D5 Plus
#  - unit: 4
#    type: g3
#    devices:
#      1: Riing Plus
#      2: Riing Plus
#      3: Riing Plus
#      4: Pacific V-GTX 1080Ti Plus GPU Waterblock
#      5: Lumi Plus LED Strip
#  - unit: 5
#    type: g3
#    devices:
#      1: Riing Plus
#      2: Riing Plus
#      3: Riing Plus
#      4: Riing Plus
#      5: Lumi Plus LED Strip

fan_manager:
  model: locked_speed
  speed: 50

#  model: temp_target
#  target: 38
#  sensor_name: k10temp
#  multiplier: 5

#  model: curve
#  points:
#    - [0, 0]  # [temp(*C), speed(0-100%)]
#    - [50, 30]
#    - [70, 100]
#  sensor_name: k10temp

lighting_manager:
# speed: normal

#  model: temperature
#  sensor_name: k10temp
#  cold: 30
#  target: 40
#  hot: 60
#  speed: extreme

#  model: alternating
#  odd_rgb:
#    r: 50
#    g: 0
#    b: 0
#  even_rgb:
#    r: 0
#    g: 50
#    b: 0

  model: full
  r: 40
  g: 0
  b: 0

# model: flow

# model: spectrum

#  model: ripple
#  r: 50
#  g: 0
#  b: 0

#  model: blink
#  r: 50
#  g: 0
#  b: 0

#  model: pulse
#  r: 50
#  g: 0
#  b: 0

